### ISSUE TITLE
Question: Are the generated lake watershed polygons available through the LAGSO package? 

### ISSUE THREAD

**Issue by lawinslow** [cont-limno/LAGOS#47]
Inquiring minds want to know.

**Comment by limnoliver** [comment]
I'm fairly certain they will be published along with the data paper. Don't think we are currently set up to retrieve them via the package. @jsta do you know the plans for this?

**Comment by soranno** [comment]
The lake watersheds will be available on EDI in September with the data paper.

If you want before then just email me!


Sent from my phone

On Aug 8, 2017, at 1:44 PM, Luke Winslow <notifications@github.com<mailto:notifications@github.com>> wrote:


-

**Comment by lawinslow** [comment]
ok, Thanks! Will do!
